INSERT INTO nip_state (id, nip_state) VALUES (1, 'Draft');
INSERT INTO nip_state (id, nip_state) VALUES (2, 'Pending approval');
INSERT INTO nip_state (id, nip_state) VALUES (3, 'Amendment required');
INSERT INTO nip_state (id, nip_state) VALUES (4, 'Approved');
INSERT INTO nip_state (id, nip_state) VALUES (5, 'Rejected');

INSERT INTO nip_role (id, role) VALUES (1, 'ADMIN');
INSERT INTO nip_role (id, role) VALUES (2, 'USER');
INSERT INTO nip_role (id, role) VALUES (3, 'APPROVER');

INSERT INTO nip_user (ID, NAME, PASSWORD, ROLE, ENABLED) VALUES (1, 'cez', 'cez', 'role_admin', 1);
INSERT INTO nip_user (ID, NAME, PASSWORD, ROLE, ENABLED) VALUES (2, 'mich', 'mich', 'role_user', 1);
INSERT INTO nip_user (ID, NAME, PASSWORD, ROLE, ENABLED) VALUES (3, 'tar', 'tar', 'role_user', 1);

BEGIN
  INSERT_INTO_NIP('nip_test1', SYSDATE - 50, SYSDATE + 150, INTERVAL '30' DAY, 1);
  INSERT_INTO_NIP('nip_test2', SYSDATE + 10, SYSDATE + 30, INTERVAL '7' DAY, 1);
  INSERT_INTO_NIP('nip_test3', SYSDATE + 10, SYSDATE + 100, INTERVAL '10' DAY, 1);
  INSERT_INTO_NIP('nip_test4', SYSDATE + 10, SYSDATE + 300, INTERVAL '60' DAY, 1);
  INSERT_INTO_NIP('nip_test5', SYSDATE + 10, SYSDATE + 400, INTERVAL '90' DAY, 1);
END;

BEGIN
  INSERT_INTO_NIP('nip_test1', SYSDATE - 50, SYSDATE + 150, INTERVAL '30' DAY, 1);

  INSERT INTO USER_ROLE_NIPS (NIP_ID, NIP_NAME, NAME, USER_ROLE) VALUES (100, 'nip_test1', 'mich', 'APPROVER');
  INSERT INTO USER_ROLE_NIPS (NIP_ID, NIP_NAME, NAME, USER_ROLE) VALUES (100, 'nip_test1', 'tar', 'USER');

  UPDATE_NIP(100, 'nip_test_change', SYSDATE + 10, SYSDATE + 200, INTERVAL '30' DAY, 3, 2);
  UPDATE_NIP_STATE(100, 3, 2, 2);
  UPDATE_NIP_STATE(100, 2, 4, 3);

  INSERT_INTO_NIP('nip_test2', SYSDATE + 10, SYSDATE + 30, INTERVAL '7' DAY, 1);
  INSERT INTO USER_ROLE_NIPS (NIP_ID, NIP_NAME, NAME, USER_ROLE) VALUES (101, 'nip_test2', 'mich', 'APPROVER');
  INSERT INTO USER_ROLE_NIPS (NIP_ID, NIP_NAME, NAME, USER_ROLE) VALUES (101, 'nip_test2', 'tar', 'USER');
  UPDATE_NIP_STATE(101, 3, 2, 2);
  UPDATE_NIP_STATE(101, 2, 3, 3);

  INSERT_INTO_NIP('nip_test3', SYSDATE + 10, SYSDATE + 100, INTERVAL '10' DAY, 1);
  INSERT INTO USER_ROLE_NIPS (NIP_ID, NIP_NAME, NAME, USER_ROLE) VALUES (102, 'nip_test3', 'mich', 'APPROVER');
  INSERT INTO USER_ROLE_NIPS (NIP_ID, NIP_NAME, NAME, USER_ROLE) VALUES (102, 'nip_test3', 'tar', 'USER');
  UPDATE_NIP_STATE(102, 3, 2, 2);
  UPDATE_NIP_STATE(102, 2, 5, 3);

  INSERT_INTO_NIP('nip_test4', SYSDATE + 10, SYSDATE + 300, INTERVAL '60' DAY, 1);
  INSERT INTO USER_ROLE_NIPS (NIP_ID, NIP_NAME, NAME, USER_ROLE) VALUES (103, 'nip_test4', 'mich', 'APPROVER');
  INSERT INTO USER_ROLE_NIPS (NIP_ID, NIP_NAME, NAME, USER_ROLE) VALUES (103, 'nip_test4', 'tar', 'USER');

  INSERT_INTO_NIP('nip_test5', SYSDATE + 10, SYSDATE + 400, INTERVAL '90' DAY, 1);
  INSERT INTO USER_ROLE_NIPS (NIP_ID, NIP_NAME, NAME, USER_ROLE) VALUES (104, 'nip_test5', 'mich', 'APPROVER');
  INSERT INTO USER_ROLE_NIPS (NIP_ID, NIP_NAME, NAME, USER_ROLE) VALUES (104, 'nip_test5', 'tar', 'USER');
  UPDATE_NIP_STATE(104, 3, 2, 2);
END;
/

